name: road_safe_ai
description: A driver drowsiness detection app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  
  # UI
  google_fonts: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.2
  network_info_plus: ^7.0.0
  vibration: ^3.1.3
  cloud_firestore: ^6.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true